trigger:
- master

pool:
  vmImage: 'windows-latest'
steps:
- task: DotNetCoreCLI@2
  displayName: 'Build and Package'
  inputs:
    command: 'pack'
    packagesToPack: 'src/Farmer'
    configuration: Release
    versioningScheme: 'off'
    verbosityPack: 'Normal'
- task: PublishBuildArtifacts@1
  displayName: Store NuGet Package
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'FarmerPackage'
    publishLocation: 'Container'