trigger:
- master
strategy:
  matrix:
    Linux:
      imageName: 'ubuntu-latest'
    Windows:
      imageName: 'windows-latest'
pool:
  vmImage: $(imageName)
steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    configuration: Release
- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    configuration: Release
    command: 'test'
    arguments: '-v n'
- task: DotNetCoreCLI@2
  displayName: 'Package'
  inputs:
    command: 'pack'
    packagesToPack: 'src/Farmer'
    configuration: Release
    versioningScheme: 'off'
    verbosityPack: 'Normal'
- task: PublishBuildArtifacts@1
  displayName: Store NuGet Package
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'FarmerPackage-$(imageName)'
    publishLocation: 'Container'